# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1689c7f9f38d65ea652e76d87fec604ecdc76bd7bd1903ec8082c723b51bd6e97e3e4a80d26bb10e6e05b4fe5c2f764344cbdfec264a13567e30197b04147911

test:
  secret_key_base: 6e6c6765d0b338b0fe181c7db7f8e6d808930c39cf775f9f59516575808d9525f19cfcfad82e6df0f1ea6a49b24a58fe8a3cfd26c02def20fecf5854bf30fb69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
